### ISSUE TITLE
docker 镜像在mac os 上运行失败

### ISSUE THREAD

**Issue by bluetianx** [dinghao188/rcore-tutorial-v3-docker#1]
hi,非常感谢你制作的镜像，我今天mac os 上拉取并运行镜像后，执行 make run 命令后，出现了错误信息：

```
Compiling object v0.26.0
error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/anyhow-1.0.42/src/error.rs:606:14
    |
606 |         ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
    |              ^^^^^^^ could not find `addr_of` in `ptr`

error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/anyhow-1.0.42/src/error.rs:647:22
    |
647 |                 ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
    |                      ^^^^^^^ could not find `addr_of` in `ptr`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `anyhow`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-binutils v0.3.3`, intermediate artifacts can be found at `/tmp/cargo-installySf8j7`

Caused by:
  build failed
Makefile:38: recipe for target 'env' failed
make: *** [env] Error 101
```

想请教一下解决方案

**Comment by dinghao188** [comment]
> hi,非常感谢你制作的镜像，我今天mac os 上拉取并运行镜像后，执行 make run 命令后，出现了错误信息：
> 
> ```
> Compiling object v0.26.0
> error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
>    --> /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/anyhow-1.0.42/src/error.rs:606:14
>     |
> 606 |         ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
>     |              ^^^^^^^ could not find `addr_of` in `ptr`
> 
> error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
>    --> /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/anyhow-1.0.42/src/error.rs:647:22
>     |
> 647 |                 ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
>     |                      ^^^^^^^ could not find `addr_of` in `ptr`
> 
> error: aborting due to 2 previous errors
> 
> For more information about this error, try `rustc --explain E0433`.
> error: could not compile `anyhow`
> 
> To learn more, run the command again with --verbose.
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `cargo-binutils v0.3.3`, intermediate artifacts can be found at `/tmp/cargo-installySf8j7`
> 
> Caused by:
>   build failed
> Makefile:38: recipe for target 'env' failed
> make: *** [env] Error 101
> ```
> 
> 想请教一下解决方案

应该是上面的代码太旧了，更新一下吧

**Comment by bluetianx** [comment]
ok 多谢啦 重新拉取代码就好了，
