### ISSUE TITLE
WSL2 Docker Container 中 make run  失败 

### ISSUE THREAD

**Issue by ccycong** [dinghao188/rcore-tutorial-v3-docker#2]
- winver  
![image](https://user-images.githubusercontent.com/22784675/132635535-3baea8f5-2526-40f8-b03c-03c201a6bd19.png)

- git仓库   ![image](https://user-images.githubusercontent.com/22784675/132635078-4be91b29-b7e6-4603-b1af-fdd

78988f731.png)
- make docker  
 
![image](https://user-images.githubusercontent.com/22784675/132635187-1b963758-a370-414d-9f21-19c9e07c8995.png)
- docker 内 uname -a
![image](https://user-images.githubusercontent.com/22784675/132635776-5d87acea-7b06-48ed-b057-45a7f005abc5.png)

- rustc工具链  
  
![image](https://user-images.githubusercontent.com/22784675/132635309-c78e9285-3b1e-44e4-86a2-3fa93de5e3b9.png)

- make run 文件
[Error.txt](https://github.com/dinghao188/rcore-tutorial-v3-docker/files/7134154/Error.txt)
- make run 截图  
![image](https://user-images.githubusercontent.com/22784675/132637308-d7542239-c8c4-4d79-a839-def429cb86cb.png)

make run 输出很长 我贴了文件 麻烦您下载查看

**Comment by ccycong** [comment]
安装了ubuntu1804-LTS虚拟机并修改 os/src/main.rs后
make run成功     
- --- 
     
需要修改 os/src/main.rs，删除第六行   
#![feature(const_in_array_repeat_expressions)]   
原因为在rustc 1.57.0-nightly (fdf65053e 2021-09-07) 中报错[ feature has been removed ] 导致make run 失败  

删除改行代码的影响不明(目前不了解rust相关知识)，我会在rCorev3官方库中重提该issus   
   
此外，在wsl2中    
尝试过 
wsl --update     
wsl --update --rollback      对wsl2 内核进行升级 降级  
使用 各个版本的rust toolchain    

 均以失败告终

**Comment by ccycong** [comment]
https://github.com/rcore-os/rCore-Tutorial-v3/pull/28   
已有相关pr ,但是并未合入main分支

**Comment by dinghao188** [comment]
> [rcore-os/rCore-Tutorial-v3#28](https://github.com/rcore-os/rCore-Tutorial-v3/pull/28)
> 已有相关pr ,但是并未合入main分支

嗯，等他们改吧
